

# This file was *autogenerated* from the file abc_ideal_membership.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_11 = Integer(11); _sage_const_6 = Integer(6)# Problem 8.11 of Chapter 2

from sage.rings.polynomial.toy_buchberger import buchberger

R = PolynomialRing(QQ, order='lex', names=('a', 'b', 'c',)); (a, b, c,) = R._first_ngens(3)

I = R.ideal([a + b + c - _sage_const_3 ,
             a**_sage_const_2  + b**_sage_const_2  + c**_sage_const_2  - _sage_const_5 ,
             a**_sage_const_3  + b**_sage_const_3  + c**_sage_const_3  - _sage_const_7 ,
             ])

# part a
print(f"{a**_sage_const_4  + b**_sage_const_4  + c**_sage_const_4  - _sage_const_9  in I}") # true

# part b
print(f"{a**_sage_const_5  + b**_sage_const_5  + c**_sage_const_5  - _sage_const_11  in I}") # false

# part c
print(f"a^5 + b^5 + c^5 = {I.reduce(a**_sage_const_5  + b**_sage_const_5  + c**_sage_const_5 )}") # 29/3
print(f"a^6 + b^6 + c^6 = {I.reduce(a**_sage_const_6  + b**_sage_const_6  + c**_sage_const_6 )}") # 29/3

